version: 2
ethernets:
  interface1:
    match:
      name: 
        e*
    dhcp4: false
    addresses:
     - ${IP_ADDRESS}
    gateway4: ${GATEWAY}
    nameservers:
      addresses: 
        - 1.1.1.1
        - 8.8.8.8